import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { publicApi } from "../api/client";
import SurgeRing from "../components/SurgeRing";
import "./LandingPage.css";

export default function LandingPage() {
  const [stats, setStats] = useState({ cities: 16, matches: 49, categories: 5, languages: 3 });

  useEffect(() => {
    publicApi.stats().then((r) => setStats(r.data)).catch(() => {});
  }, []);

  return (
    <div className="landing">
      <section className="hero mesh-hero grid-bg">
        <div className="hero-inner">
          <div className="hero-left">
            <span className="badge badge-purple pulse">⚡ FIFA WORLD CUP 2026</span>
            <h1 className="hero-title">
              60,000 fans are coming.<br />
              <span className="text-purple">Is your business ready?</span>
            </h1>
            <p className="hero-sub">
              SurgeMind is an AI agent that monitors every FIFA 2026 match across 16 US cities and tells your business exactly what to do before the surge hits.
            </p>
            <div className="hero-ctas">
              <Link to="/signup" className="btn btn-primary">Get Early Access →</Link>
              <Link to="/signin" className="btn btn-ghost">Watch Demo ▶</Link>
            </div>
          </div>
          <div className="hero-right">
            <div className="alert-mockup card float-card">
              <div className="mock-header">🌮 Maria&apos;s Taco Shop, Dallas</div>
              <SurgeRing score={8.5} size={140} />
              <ul className="mock-checklist">
                <li>☐ Stock 3× beef inventory — 60k fans Friday</li>
                <li>☐ Hire 2 extra staff Sat–Sun</li>
                <li>☐ Add Spanish to menu — 60% Argentine fans</li>
              </ul>
              <p className="mock-footer">Generated by SurgeMind AI · 2 minutes ago</p>
            </div>
          </div>
        </div>
      </section>

      <section className="stats-bar">
        {[
          [stats.cities, "US Cities Covered"],
          [stats.matches, "FIFA Matches Tracked"],
          [stats.categories, "Business Categories"],
          [stats.languages, "Languages Supported"],
        ].map(([n, l], i) => (
          <React.Fragment key={l}>
            {i > 0 && <div className="stat-divider" />}
            <div className="stat-item">
              <div className="stat-num">{n}</div>
              <div className="label">{l}</div>
            </div>
          </React.Fragment>
        ))}
      </section>

      <section className="section container">
        <p className="section-label">HOW IT WORKS</p>
        <h2>Your AI advisor. Always 7 days ahead.</h2>
        <div className="steps">
          {[
            ["📡", "Monitors Matches", "Tracks all 49 FIFA 2026 matches across 16 US host cities in real time."],
            ["🧠", "Calculates Surge", "Combines crowd forecasts, fan nationalities, and your business type into a 1–10 surge score."],
            ["⚡", "Sends Action Plan", "Delivers specific inventory, staffing, and menu advice before fans arrive."],
          ].map(([icon, title, desc]) => (
            <div key={title} className="card step-card">
              <span className="step-icon">{icon}</span>
              <h3>{title}</h3>
              <p>{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="section container">
        <div className="biz-pills">
          {["🍕 Restaurant", "🍺 Bar & Brewery", "🏨 Hotel", "🛍️ Retail", "☕ Cafe"].map((p, i) => (
            <span key={p} className={`biz-pill ${i === 0 ? "active" : ""}`}>{p}</span>
          ))}
        </div>
      </section>

      <section className="section container testimonial card">
        <span className="quote-mark">"</span>
        <blockquote>
          SurgeMind told us a surge was coming 5 days early. We made $4,000 extra that weekend.
        </blockquote>
        <cite>Maria G. — Taco Shop Owner, Dallas, TX · ★★★★★</cite>
      </section>

      <section className="footer-cta mesh-hero">
        <h2>The World Cup starts June 11. Get ready now.</h2>
        <Link to="/signup" className="btn btn-primary">Start Free →</Link>
        <p className="footer-links"><Link to="/">Privacy</Link> · <Link to="/">Terms</Link> · <Link to="/">Contact</Link></p>
      </section>
    </div>
  );
}
